name: Cypress Tests on PR

on: pull_request

jobs:
 cypress-test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Run Cypress
       uses: cypress-io/github-action@v5
       with:
         browser: chrome
         config-file: cypress.prod.config.js